export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ERROR_DISPATCH = "ERROR_DISPATCH";
export const GET_LOCATION_FORCAST = "GET_LOCATION_FORCAST";
export const SET_SPINNER = "SET_SPINNER";
